### ISSUE TITLE
Establish criteria and process for adding new member to Crossplane org

### ISSUE THREAD

**Issue by hasheddan** [crossplane/org#1]
Up until this point, members have been added to the Crossplane org on an as-needed basis. This process should be formalized to reduce friction and confusion around adding new contributors.

**Comment by jbw976** [comment]
The current process for adding members to the Crossplane org can be found in the governance: https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members

We can make it more formal though, i.e. with a PR to request or nominate membership, definitely open for improvements! :)
