### ISSUE TITLE
MEMBERSHIP: zzxwill

### ISSUE THREAD

**Issue by zzxwill** [crossplane/org#10]
---
name: Organization Membership Request
about: Request membership in Crossplane Org
title: 'MEMBERSHIP: zzxwill'

---

### GitHub Username
zzxwill

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [x] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [x] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [x] I am actively contributing to the Crossplane project
- [x] I have two sponsors that are current Crossplane Org members
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @hongchaodeng 
- @hasheddan 

### List of contributions to the Crossplane project
- PRs reviewed / authored
https://github.com/crossplane/crossplane/pull/1560
https://github.com/crossplane/crossplane/pull/1562
https://github.com/crossplane/crossplane/pull/1580
https://github.com/crossplane/provider-alibaba/pull/58
https://github.com/crossplane/provider-alibaba/pull/61
https://github.com/crossplane/provider-alibaba/pull/62
https://github.com/crossplane/provider-alibaba/pull/75
https://github.com/crossplane/provider-alibaba/pull/77
https://github.com/crossplane/provider-alibaba/pull/79
https://github.com/crossplane/provider-alibaba/pull/80
https://github.com/crossplane/provider-alibaba/pull/81
https://github.com/crossplane/provider-alibaba/pull/82
https://github.com/crossplane/provider-alibaba/pull/84
https://github.com/crossplane/provider-alibaba/pull/87
https://github.com/crossplane/provider-alibaba/pull/88 (co-authored with @xiqiu618)
https://github.com/crossplane/provider-alibaba/pull/89
https://github.com/crossplane/provider-alibaba/pull/90
https://github.com/crossplane/provider-alibaba/pull/91
https://github.com/crossplane/provider-alibaba/pull/92
https://github.com/crossplane/provider-alibaba/pull/93
  
- Issues responded to
https://github.com/crossplane/crossplane/issues/1558
https://github.com/crossplane/crossplane/issues/1561
https://github.com/crossplane/crossplane/issues/1575
https://github.com/crossplane/crossplane/issues/1578

**Comment by hasheddan** [comment]
+1 from me! Thank you for all of the contributions you have already made @zzxwill :)

**Comment by hongchaodeng** [comment]
+1 from me! Thanks for the awesome work you have made.

**Comment by jbw976** [comment]
+1! I'll get a PR together to add @zzxwill as a member :)

**Comment by jbw976** [comment]
PR is https://github.com/crossplane/org/pull/11

**Comment by jbw976** [comment]
An invitation to join the organization has been sent to @zzxwill

**Comment by jbw976** [comment]
@zzxwill is now a member of the crossplane org, and also added as a maintainer on https://github.com/crossplane/provider-alibaba.

Looking forward to all of your continued efforts and contributions @zzxwill! 💪 🙇‍♂️
