### ISSUE TITLE
MEMBERSHIP: tnthornton

### ISSUE THREAD

**Issue by tnthornton** [crossplane/org#12]
### GitHub Username
@tnthornton

### Requirements
- [X] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [X] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [X] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [X] I am actively contributing to the Crossplane project
- [X] I have two sponsors that are current Crossplane Org members
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jbw976 
- @hasheddan 

### List of contributions to the Crossplane project
- PRs reviewed / authored
- currently working on https://github.com/crossplane/provider-aws/issues/85

**Comment by jbw976** [comment]
+1 for me, @tnthornton contribution for adding EC2 instance support will be great for the community!

**Comment by hasheddan** [comment]
+1 from me, welcome @tnthornton!

**Comment by jbw976** [comment]
@tnthornton, you have been sent an invite to join the crossplane org :)

**Comment by tnthornton** [comment]
Sweeet, thanks!
