### ISSUE TITLE
MEMBERSHIP: chlunde

### ISSUE THREAD

**Issue by chlunde** [crossplane/org#16]
### GitHub Username
@chlunde

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [x] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [x] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [x] I am actively contributing to the Crossplane project
- [x] I have two sponsors that are current Crossplane Org members
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @negz 
- @hasheddan 

### List of contributions to the Crossplane project
PRs reviewed / authored
- https://github.com/crossplane/provider-aws/pull/571
- https://github.com/crossplane/provider-aws/pull/617
- https://github.com/crossplane/provider-aws/pull/626
- https://github.com/crossplane/provider-aws/pull/629
- https://github.com/crossplane/provider-aws/pull/633
- https://github.com/crossplane/provider-aws/pull/743
- https://github.com/crossplane/provider-aws/pull/759
- https://github.com/crossplane/provider-aws/pull/761
- https://github.com/crossplane/provider-aws/pull/764
- https://github.com/crossplane/provider-aws/pull/765
- https://github.com/crossplane/crossplane/pull/2455
open
- https://github.com/crossplane/provider-aws/pull/794
- ...
Issues responded to
- https://github.com/crossplane/crossplane/issues/2454
- https://github.com/crossplane/crossplane/issues/2290#issuecomment-846184238

**Comment by hasheddan** [comment]
+1 from me! Grateful for your contributions and looking forward to your continued leadership 🎉

**Comment by jbw976** [comment]
+1 from me for sure! A ton of value that @chlunde has been adding to the project :)

**Comment by jbw976** [comment]
I will go ahead and open a PR to add @chlunde to the org membership

**Comment by jbw976** [comment]
@chlunde an invitation from Github has been sent out to you now!

**Comment by chlunde** [comment]
@jbw976 thanks, accepted :)
