### ISSUE TITLE
MEMBERSHIP: Feggah

### ISSUE THREAD

**Issue by Feggah** [crossplane/org#18]
### GitHub Username
@Feggah

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [x] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [x] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [x] I am actively contributing to the Crossplane project
- [x] I have two sponsors that are current Crossplane Org members
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @turkenh 
- @negz 

### List of contributions to the Crossplane project
- PRs reviewed / authored
  - https://github.com/crossplane/crossplane/pull/2626
  - https://github.com/crossplane-contrib/provider-github/pull/13
  - https://github.com/crossplane/provider-gcp/pull/358
  - https://github.com/crossplane/provider-gcp/pull/390
  - https://github.com/crossplane/provider-gcp/pull/383
  - https://github.com/crossplane/provider-gcp/pull/391
  - https://github.com/crossplane/provider-gcp/pull/387
  - https://github.com/crossplane/provider-gcp/pull/386
  - https://github.com/crossplane/provider-gcp/pull/384
- Pull requests below were reviewed before sending to the community
  - https://github.com/stone-payments/provider-azure/pull/3
  - https://github.com/stone-payments/provider-github/pull/7
- Issues responded to
  - https://github.com/crossplane-contrib/provider-github/issues/15
  - https://github.com/crossplane/provider-gcp/issues/388
  - https://github.com/crossplane/provider-gcp/issues/389
  - https://github.com/crossplane/provider-gcp/issues/350
  - https://github.com/crossplane/crossplane/issues/2611
  - https://github.com/crossplane/crossplane/issues/2528
  - https://github.com/crossplane/provider-gcp/issues/337

**Comment by negz** [comment]
+1 - Thanks for all your help so far @Feggah!
