### ISSUE TITLE
MEMBERSHIP: haarchri

### ISSUE THREAD

**Issue by haarchri** [crossplane/org#20]
### GitHub Username
@haarchri

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [x] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [x] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [x] I am actively contributing to the Crossplane project
- [x] I have two sponsors that are current Crossplane Org members
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @negz 
- @hasheddan 

### List of contributions to the Crossplane project
- PRs reviewed / authored
https://github.com/crossplane/provider-aws/pull/888
https://github.com/crossplane/provider-aws/pull/686
https://github.com/crossplane/provider-aws/pull/730
https://github.com/crossplane/provider-aws/pull/852
https://github.com/crossplane/provider-aws/pull/829
https://github.com/crossplane/provider-aws/pull/754
https://github.com/crossplane/provider-aws/pull/752
https://github.com/crossplane/provider-aws/pull/751
https://github.com/crossplane/provider-aws/pull/746
https://github.com/crossplane/provider-aws/pull/744
https://github.com/crossplane/provider-aws/pull/733
https://github.com/crossplane/provider-aws/pull/694
https://github.com/crossplane/provider-aws/pull/884
https://github.com/crossplane/provider-aws/pull/831
https://github.com/crossplane/provider-aws/pull/779
https://github.com/crossplane/provider-aws/pull/771
https://github.com/crossplane-contrib/provider-helm/pull/111
https://github.com/crossplane-contrib/provider-kubernetes/pull/6
https://github.com/upbound/build/pull/168

- Issues responded to
https://github.com/crossplane/provider-aws/issues/880
https://github.com/crossplane/provider-aws/issues/844
https://github.com/crossplane/provider-aws/issues/842
https://github.com/crossplane/provider-aws/issues/799
https://github.com/crossplane/provider-aws/issues/747
https://github.com/crossplane/provider-aws/issues/738
https://github.com/crossplane/provider-aws/issues/685
https://github.com/crossplane/provider-aws/issues/610

**Comment by hasheddan** [comment]
+1 from me! Thank you so much for everything you have and will contribute!

**Comment by negz** [comment]
Just edited to add @hasheddan as a sponsor. :)
