### ISSUE TITLE
MEMBERSHIP: sergenyalcin

### ISSUE THREAD

**Issue by sergenyalcin** [crossplane/org#22]
### GitHub Username

@sergenyalcin

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [x] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [x] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [x] I am actively contributing to the Crossplane project
- [x] I have two sponsors that are current Crossplane Org members
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jbw976 
- @turkenh 

### List of contributions to the Crossplane project
- I'm currently working on [this issue](https://github.com/crossplane/provider-gcp/issues/360).

**Comment by jbw976** [comment]
+1 indeed for me - @sergenyalcin is making a long term commitment to the Crossplane project and is getting started with his first major contribution of provider-gcp support in https://github.com/crossplane/provider-gcp/issues/360.

**Comment by turkenh** [comment]
+1 - looking forward for your contributions @sergenyalcin 🙌

**Comment by jbw976** [comment]
@sergenyalcin, I've sent you an invite to join the Crossplane org.  Welcome to the team!! 🙇‍♂️
