### ISSUE TITLE
MEMBERSHIP: stevendborrelli

### ISSUE THREAD

**Issue by stevendborrelli** [crossplane/org#24]
### GitHub Username
e.g. @stevendborrelli

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [x] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [x] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [x] I am actively contributing to the Crossplane project
- [x] I have two sponsors that are current Crossplane Org members
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @hasheddan 
- @muvaf 

### List of contributions to the Crossplane project
- Contributed multiple PRs to [provider-kafka](https://github.com/crossplane-contrib/provider-kafka)
- Provider AWS PRs: https://github.com/crossplane/provider-aws/pull/929, https://github.com/crossplane/provider-aws/pull/922
- Issues responded to https://github.com/crossplane/provider-aws/pull/937

**Comment by hasheddan** [comment]
+1 from me!

**Comment by muvaf** [comment]
Thank you for your contributions @stevendborrelli ! +1 !

**Comment by muvaf** [comment]
I'll open the PR

**Comment by stevendborrelli** [comment]
I am part of the org now. Thanks!
