### ISSUE TITLE
MEMBERSHIP: @mcbenjemaa

### ISSUE THREAD

**Issue by mcbenjemaa** [crossplane/org#27]
### GitHub Username

@mcbenjemaa

### Requirements
- [X] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [X] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [X] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [X] I am actively contributing to the Crossplane project
- [X] I have two sponsors that are current Crossplane Org members
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @hasheddan 
- @negz 

### List of contributions to the Crossplane project
- PRs reviewed / authored

   * c/c: 
       * Include imagePullSecrets to rbac-manager serviceaccount: https://github.com/crossplane/crossplane/pull/2782 
       * Add podSecurityContext https://github.com/crossplane/crossplane/pull/2692
       * Adding string transform ToUpper/ToLower https://github.com/crossplane/crossplane/pull/2592
 
  * c/provider-azure: 
     * publicNetworkAccess https://github.com/crossplane/provider-azure/pull/301
  
   * c/provider-gcp: 
     * cloudsql replica WIP,,https://github.com/crossplane/provider-gcp/pull/409
     
- Issues responded to

   * Proposal: Adding fromCompositeFieldPath to connectionDetails https://github.com/crossplane/crossplane/issues/2560
   * Support: https://github.com/crossplane/crossplane/issues/2700
   * String Transform: https://github.com/crossplane/crossplane/issues/2579
   * provider-helm: https://github.com/crossplane-contrib/provider-helm/issues/100
   * imagePullSecrets: https://github.com/crossplane/crossplane/issues/2781
   * podSecurityContext fsGroup https://github.com/crossplane/crossplane/issues/2694

**Apart from that** Me and my colleague have started to add support for certain provider and will probably donate it to @crossplane-contrib

**Comment by hasheddan** [comment]
+1 from me! Thank you for the contributions you have already made!

**Comment by negz** [comment]
+1 - Thank you!

**Comment by jbw976** [comment]
An invitation has now been sent to you @mcbenjemaa to join the crossplane org, now that #31 has been merged.  Thank you for your contributions and welcome to the Crossplane org! 💪

**Comment by negz** [comment]
I'm pretty sure this one was done. :)
