### ISSUE TITLE
MEMBERSHIP: ezgidemirel

### ISSUE THREAD

**Issue by ezgidemirel** [crossplane/org#28]
### GitHub Username
@ezgidemirel

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [x] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [x] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [x] I am actively contributing to the Crossplane project
- [x] I have two sponsors that are current Crossplane Org members
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @muvaf 
- @turkenh 
- @jbw976 

### List of contributions to the Crossplane project
- [PRs reviewed / authored](https://github.com/crossplane/provider-aws/pull/1099)

**Comment by jbw976** [comment]
+1 for sure from me! 💯

**Comment by jbw976** [comment]
@ezgidemirel you have been sent an invitation to join the Crossplane org.  Thank you for your recent contributions, and even more so your future contributions that are coming down the road 😊 🙇‍♂️
