### ISSUE TITLE
MEMBERSHIP: @ytsarev

### ISSUE THREAD

**Issue by ytsarev** [crossplane/org#30]
### GitHub Username
@ytsarev

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [x] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [x] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [x] I am actively contributing to the Crossplane project
- [x] I have two sponsors that are current Crossplane Org members
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jbw976 
- @muvaf 

### List of contributions to the Crossplane project
- https://github.com/crossplane-contrib/provider-terraform/pulls?q=is%3Apr+author%3Aytsarev
- https://github.com/crossplane-contrib/provider-jet-rancher
- https://www.youtube.com/watch?v=5l4Xf_Q8ybY

**Comment by muvaf** [comment]
+1 from me!

**Comment by jbw976** [comment]
+1 from me for sure! I will follow up with the PR today :)

**Comment by jbw976** [comment]
An invitation has been sent to @ytsarev to join the org now that #31 is merged.  Thank you for your contributions @ytsarev!
