### ISSUE TITLE
MEMBERSHIP: @Ruhika1417 

### ISSUE THREAD

**Issue by Ruhika1417** [crossplane/org#33]
### GitHub Username
@Ruhika1417

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [x] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [x] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [x] I am actively contributing to the Crossplane project
- [x] I have two sponsors that are current Crossplane Org members
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jbw976 
- @muvaf 

### List of contributions to the Crossplane project
- Issues responded to/Currently working on:
  - https://github.com/crossplane-contrib/provider-gcp/issues/442
- LFX Mentorship project
    -  https://mentorship.lfx.linuxfoundation.org/project/06fe8a5b-c3b9-4d12-975f-19f5ec49d006

**Comment by jbw976** [comment]
Definitely +1 this, @Ruhika1417 is working on a LFX Mentorship project this summer and will be an important part of the community :)

**Comment by jbw976** [comment]
An invitation has been sent to @Ruhika1417 to officially join the org :)

**Comment by Ruhika1417** [comment]
yay! Thanks a lot, Jared and Muvaffak! Glad to be a part of Crossplane as a Member.
