### ISSUE TITLE
MEMBERSHIP: @parul5sahoo

### ISSUE THREAD

**Issue by parul5sahoo** [crossplane/org#36]
### GitHub Username
@parul5sahoo

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [x] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [x] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [x] I am actively contributing to the Crossplane project
- [x] I have two sponsors that are current Crossplane Org members
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jbw976 
- @hasheddan 

### List of contributions to the Crossplane project
- Selected to serve as an LFX Mentee to Crossplane and working on https://github.com/crossplane/crossplane/issues/2876
- I responded to [this issue](https://github.com/crossplane/crossplane/issues/3157)

**Comment by jbw976** [comment]
An invitation to join the org has been sent to @parul5sahoo 💪
