### ISSUE TITLE
MEMBERSHIP: bobh66

### ISSUE THREAD

**Issue by bobh66** [crossplane/org#38]
### GitHub Username
@bobh66

### Requirements
- [X] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [X] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [X] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [X] I am actively contributing to the Crossplane project
- [X] I have two sponsors that are current Crossplane Org members
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @negz 
- @jbw976 

### List of contributions to the Crossplane project
- https://github.com/crossplane/crossplane/pull/3213
- https://github.com/crossplane/crossplane/pull/3072
- https://github.com/crossplane/crossplane/pull/3040
- https://github.com/crossplane/crossplane/issues/3225

Also contributions to provider-aws, provider-kubernetes and currently a Maintainer of provider-terraform

**Comment by negz** [comment]
+1 - Bob has been driving a lot of work in the community.

**Comment by jbw976** [comment]
+1 on Bob - he's been doing great work and contributing thoughtful ideas/designs 💪 .  We'd be happy for more!

**Comment by jbw976** [comment]
Invite has been sent to @bobh66!
