### ISSUE TITLE
MEMBERSHIP: @jastang

### ISSUE THREAD

**Issue by jastang** [crossplane/org#39]
### GitHub Username
@jastang

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [x] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [x] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [x] I am actively contributing to the Crossplane project
- [x] I have two sponsors that are current Crossplane Org members
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @negz
- @jbw976

### List of contributions to the Crossplane project
- Working with awesome folks @ Upbound!
- Occasional engagement in Crossplane Slack helping answer questions

**Comment by negz** [comment]
+1 - Jason is leading a team building product around Crossplane at Upbound. Thanks @jastang!

**Comment by jbw976** [comment]
+1 from me as well, excited for @jastang to have more impact on the project!

**Comment by jbw976** [comment]
Invite has been sent to @jastang!
