### ISSUE TITLE
MEMBERSHIP: rahulgrover99

### ISSUE THREAD

**Issue by rahulgrover99** [crossplane/org#4]
### GitHub Username
@rahulgrover99

### Requirements
- [X] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [X] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [X] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [X] I am actively contributing to the Crossplane project
- [X] I have two sponsors that are current Crossplane Org members
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jbw976
- @hasheddan

### List of contributions to the Crossplane project
- I will be working on [this issue](https://github.com/crossplane/test/issues/7) currently.
- I applied and got selected for LFX Mentorship at Crossplane. I will eventually be working towards solving [this issue](https://github.com/crossplane/crossplane/issues/1033) as well.

**Comment by hasheddan** [comment]
+1 from me! I'll open a PR to add as soon as we receive confirmation from @jbw976 🙂

**Comment by jbw976** [comment]
+1 from me too! Excited for @rahulgrover99 to be part of the community! 💪
