### ISSUE TITLE
MEMBERSHIP: kiote

### ISSUE THREAD

**Issue by kiote** [crossplane/org#40]
### GitHub Username
@kiote

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [x] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [x] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [x] I am actively contributing to the Crossplane project
- [x] I have two sponsors that are current Crossplane Org members
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @negz 
- @jbw976 

### List of contributions to the Crossplane project
- https://github.com/crossplane/crossplane/pull/3164/

**Comment by negz** [comment]
+1 - Thanks @kiote!

**Comment by jbw976** [comment]
+1, thank you for the great first contribution and we'll be looking forward to more from you! 🙇

**Comment by jbw976** [comment]
Invite has been sent to @kiote, welcome aboard!! 🙇 👋
