### ISSUE TITLE
MEMBERSHIP: @nullable-eth

### ISSUE THREAD

**Issue by nullable-eth** [crossplane/org#41]
### GitHub Username
@nullable-eth

### Requirements
- [X] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [X] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [X] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [X] I am actively contributing to the Crossplane project
- [X] I have two sponsors that are current Crossplane Org members
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @negz 
- @hasheddan 

### List of contributions to the Crossplane project
- Working with awesome folks @ Upbound!

**Comment by hasheddan** [comment]
+1 from me!

**Comment by negz** [comment]
+1 - Thanks @nullable-eth

**Comment by jbw976** [comment]
+1 from me, looking forward to @nullable-eth contributing more with his expertise on packages :)

**Comment by jbw976** [comment]
Invite has been sent to @nullable-eth!
