### ISSUE TITLE
MEMBERSHIP: @nlinx

### ISSUE THREAD

**Issue by nlinx** [crossplane/org#42]
### GitHub Username
@nlinx

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [x] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [x] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [x] I am actively contributing to the Crossplane project
- [x] I have two sponsors that are current Crossplane Org members
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @negz 
- @hasheddan 

### List of contributions to the Crossplane project
- Working at Upbound!

**Comment by negz** [comment]
+1 - Thanks @nlinx!

**Comment by jbw976** [comment]
+1 from me too, @nlinx will get more involved with package manager related reviews :)

**Comment by jbw976** [comment]
Invite has been sent to @nlinx!
