### ISSUE TITLE
MEMBERSHIP: iAnomaly

### ISSUE THREAD

**Issue by iAnomaly** [crossplane/org#44]
### GitHub Username
@iAnomaly

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [x] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [x] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [x] I am actively contributing to the Crossplane project
- [x] I have two sponsors that are current Crossplane Org members
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @negz 
- @hasheddan 

### List of contributions to the Crossplane project
- PRs reviewed / authored
- Issues responded to
https://github.com/crossplane/crossplane/issues?q=involves%3AiAnomaly
https://github.com/crossplane-contrib/provider-aws/issues?q=involves%3AiAnomaly

**Comment by hasheddan** [comment]
+1 from me! Thanks for your contributions @iAnomaly!

**Comment by negz** [comment]
+1 Thank you!
