### ISSUE TITLE
MEMBERSHIP: tanujd11

### ISSUE THREAD

**Issue by tanujd11** [crossplane/org#46]
### GitHub Username
@tanujd11

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [x] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [x] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [x] I am actively contributing to the Crossplane project
- [x] I have two sponsors that are current Crossplane Org members
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @negz 
- @hasheddan 

### List of contributions to the Crossplane project
- PRs reviewed / authored
https://github.com/crossplane-contrib/provider-aws/pull/1041
- Issues responded to
https://github.com/crossplane-contrib/provider-aws/issues/338

**Comment by hasheddan** [comment]
+1 from me!

**Comment by negz** [comment]
+1 - Thank you!

**Comment by jbw976** [comment]
An invite has been sent to @tanujd11 to join the crossplane org! 🎉

**Comment by tanujd11** [comment]
@jbw976 sorry to bug you again but coincidentally gmail disabled my mails due to storage. I have subscribed to increase the storage. Will the provider-github send me the mail again?
