### ISSUE TITLE
MEMBERSHIP: piotr1215

### ISSUE THREAD

**Issue by Piotr1215** [crossplane/org#49]
### GitHub Username
@piotr1215

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [x] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [x] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [x] I am actively contributing to the Crossplane project
- [x] I have two sponsors that are current Crossplane Org members
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @negz 
- @jbw976 

### List of contributions to the Crossplane project
- PRs reviewed / authored
  - https://github.com/crossplane/crossplane/pull/2946
  - https://github.com/crossplane/crossplane/pull/2970
- Discussion https://github.com/crossplane/crossplane/discussions/2967, still keeping it up to date :)

**Comment by jbw976** [comment]
+1 for me for sure! @Piotr1215 is bringing a lot of passion to the project and quickly gaining a deep understanding of the ecosystem!

**Comment by negz** [comment]
+1

**Comment by jbw976** [comment]
An invite has been sent to @Piotr1215 to join the crossplane org! 🎉
