### ISSUE TITLE
MEMBERSHIP: AlainRoy

### ISSUE THREAD

**Issue by AlainRoy** [crossplane/org#50]
### GitHub Username
@AlainRoy

### Requirements
- [X] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [X] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [X] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [X] I am actively contributing to the Crossplane project
- [X] I have two sponsors that are current Crossplane Org members
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @negz
- @jbw976

### List of contributions to the Crossplane project
- Working at Upbound

**Comment by jbw976** [comment]
+1 here - @AlainRoy is going to be leading a team of folks that contribute to the community and control plane design/arch

**Comment by jbw976** [comment]
+1 here - @AlainRoy is going to be leading a team of folks that contribute to the community and control plane design/arch

**Comment by negz** [comment]
+1

**Comment by jbw976** [comment]
An invite has been sent to @AlainRoy to join the crossplane org! 🎉
