### ISSUE TITLE
MEMBERSHIP: plumbis

### ISSUE THREAD

**Issue by plumbis** [crossplane/org#52]
### GitHub Username
@plumbis

### Requirements
- [X] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [X] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [X] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [X] I am actively contributing to the Crossplane project
- [X] I have two sponsors that are current Crossplane Org members
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jbw976 
- @hasheddan 

### List of contributions to the Crossplane project
- [Move upbound.io from Jekyll to Hugo #149](https://github.com/crossplane/crossplane.github.io/issues/149)

**Comment by hasheddan** [comment]
Big +1 from me! Welcome @plumbis :)

**Comment by jbw976** [comment]
definite +1 from me, as one could guess from https://github.com/crossplane/crossplane.github.io/pull/150#issuecomment-1238614804 😊

**Comment by jbw976** [comment]
@plumbis has been sent an invitation to join the crossplane org! 🎉
