### ISSUE TITLE
MEMBERSHIP: elohmrow

### ISSUE THREAD

**Issue by elohmrow** [crossplane/org#54]
### GitHub Username
@elohmrow

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [x] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [x] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [x] I am actively contributing to the Crossplane project
- [x] I have two sponsors that are current Crossplane Org members
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jbw976 
- @ytsarev  

### List of contributions to the Crossplane project
- PRs reviewed / authored
- Issues responded to

**Comment by jbw976** [comment]
+1 @elohmrow has been getting ramped up on Crossplane with a lot of perspective from the field and adopters - looking forward to having his opinion in the project! 💪

**Comment by ytsarev** [comment]
+1 @elohmrow you have a unique understanding of the experience of the huge spectrum of Crossplane adopters. Your ideas will be extremely valuable. Welcome!
