### ISSUE TITLE
MEMBERSHIP: @jeanduplessis

### ISSUE THREAD

**Issue by jeanduplessis** [crossplane/org#55]
### GitHub Username
@jeanduplessis

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [x] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [x] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [x] I am actively contributing to the Crossplane project
- [x] I have two sponsors that are current Crossplane Org members
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @negz 
- @jbw976 

### List of contributions to the Crossplane project
- https://github.com/crossplane/crossplane/pull/3324)
- [Responding to community members in Slack asking for help with creating providers](https://crossplane.slack.com/archives/C01718T2476/p1666348787221519?thread_ts=1666343208.274219&cid=C01718T2476)
- I manage a team at Upbound who are dedicated to pushing forward the improvement and maturation of the Crossplane framework and supporting the community through issue triaging, PR reviews, and Q&A in Slack.

**Comment by jbw976** [comment]
+1 for me, @jeanduplessis is going to be coordinating, planning, and driving a lot of features and initiatives for the community! 💪

**Comment by negz** [comment]
+1 - Thanks!

**Comment by jbw976** [comment]
@negz @bassam PR to add @jeanduplessis in #56, requires steering committee review :)

**Comment by jbw976** [comment]
@jeanduplessis has been invited to the org as a member :)
