### ISSUE TITLE
MEMBERSHIP: lsviben

### ISSUE THREAD

**Issue by lsviben** [crossplane/org#59]
### GitHub Username
@lsviben

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [x] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [x] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [x] I am actively contributing to the Crossplane project
- [x] I have two sponsors that are current Crossplane Org members
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @turkenh 
- @jeanduplessis

### List of contributions to the Crossplane project
Working at Upbound, will focus on developing and improving the Crossplane project.

**Comment by jeanduplessis** [comment]
@lsviben is a new team member to the Control Planes team at Upbound and will be working full-time on helping advance the Crossplane project.

**Comment by turkenh** [comment]
+1 from me.
Happy to have you in the team @lsviben!

**Comment by jbw976** [comment]
@lsviben has been sent an invitation to join the crossplane org - welcome aboard!! 🙇
