### ISSUE TITLE
MEMBERSHIP: pedjak

### ISSUE THREAD

**Issue by pedjak** [crossplane/org#61]
### GitHub Username

@pedjak

### Requirements
- [ ] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [ ] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [ ] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [ ] I am actively contributing to the Crossplane project
- [ ] I have two sponsors that are current Crossplane Org members
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

Sponsors

    @turkenh
    @jeanduplessis

List of contributions to the Crossplane project

Working at Upbound, will focus on developing and improving the Crossplane project.

**Comment by turkenh** [comment]
+1

**Comment by jeanduplessis** [comment]
@jbw976 would you please do the honors.
