### ISSUE TITLE
MEMBERSHIP: gberche-orange

### ISSUE THREAD

**Issue by gberche-orange** [crossplane/org#64]
### GitHub Username
gberche-orange

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [x] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [x] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [x] I am actively contributing to the Crossplane project 
- [x] I have two sponsors that are current Crossplane Org members
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
  - https://github.com/crossplane/crossplane/pull/4020#issuecomment-1538719840
  - https://github.com/crossplane/crossplane/pull/4020#issuecomment-1528881142 

### Sponsors
- @negz  
- @jbw976 

### List of contributions to the Crossplane project
- PRs reviewed / authored
- [x] Issues responded to gh issues https://github.com/search?q=org%3Acrossplane+author:gberche-orange&type=issues

**Comment by jeanduplessis** [comment]
I'm happy to sponsor @gberche-orange's membership. 

@jbw976 would you mind taking the necessary steps.

**Comment by jbw976** [comment]
@gberche-orange has been invited to join the crossplane org as a member! 💪

**Comment by gberche-orange** [comment]
thanks @jbw976 ! I confirm that I have now permissions to help reopen issues marked as stale by the bot (as needed).
