### ISSUE TITLE
MEMBERSHIP: sttts

### ISSUE THREAD

**Issue by sttts** [crossplane/org#65]
### GitHub Username
sttts

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [x] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [x] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [x] I am actively contributing to the Crossplane project
- [x] I have two sponsors that are current Crossplane Org members
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @negz 
- @pedjak

### List of contributions to the Crossplane project
- authored https://github.com/crossplane/crossplane/pull/4205

**Comment by jeanduplessis** [comment]
I support this membership request 👍

**Comment by pedjak** [comment]
+1

**Comment by jbw976** [comment]
@sttts has been invited to join the crossplane org as a member! 🙇
