### ISSUE TITLE
MEMBERSHIP: dee0sap

### ISSUE THREAD

**Issue by dee0sap** [crossplane/org#67]
### GitHub Username
dee0sap

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [x] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [x] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [x] I am actively contributing to the Crossplane project
- [x] I have two sponsors that are current Crossplane Org members
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @Feggah 
- @hasheddan 

### List of contributions to the Crossplane project
- Contributions in git can be found [here](https://github.com/search?q=+commenter%3Adee0++commenter%3Adee0sap+org%3Acrossplane+org%3Akubernetes+org%3Akubernetes-sigs+org%3Acrossplane-contrib+&type=issues)
- For those few times where I could, I have helped folks on Slack.    
- Have attended a few community meetings and in them provided descriptions of SAP uses cases and provided what info I could to help Upbound developers

**Comment by jbw976** [comment]
@dee0sap you've been sent an invite to join the crossplane org as a member! 🙇
