### ISSUE TITLE
MEMBERSHIP: smileisak

### ISSUE THREAD

**Issue by smileisak** [crossplane/org#71]
### GitHub Username
smileisak

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [x] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [x] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [x] I am actively contributing to the Crossplane project
- [x] I have two sponsors that are current Crossplane Org members
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jbw976 
- @haarchri

### List of contributions to the Crossplane project
1. The official ovh provider https://github.com/edixos/provider-ovh/
1. https://github.com/crossplane/crossplane/issues/3049
1. https://github.com/crossplane/crossplane/pull/3710
1. https://github.com/crossplane/crossplane/pull/3098
1. https://github.com/crossplane-contrib/provider-argocd/pull/106

**Comment by jbw976** [comment]
+1 on this, @smileisak has definitely been involved and an asset to the community! 💪

**Comment by haarchri** [comment]
+1 from me! Thanks for all you have contributed to the Crossplane community @smileisak

**Comment by jbw976** [comment]
You should now have an invite to join the crossplane org as a member @smileisak! welcome aboard 👋
