### ISSUE TITLE
MEMBERSHIP: mergenci

### ISSUE THREAD

**Issue by mergenci** [crossplane/org#73]
### GitHub Username

@mergenci

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [x] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [x] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [x] I am actively contributing to the Crossplane project
- [x] I have two sponsors that are current Crossplane Org members
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jbw976 
- @jeanduplessis

#### PRs authored

- https://github.com/crossplane/upjet/pull/329
- https://github.com/crossplane/upjet/pull/343
- https://github.com/crossplane/upjet/pull/350
- https://github.com/crossplane/docs/pull/560
- https://github.com/crossplane/docs/pull/569

To-be-donated-to-Crossplane [provider-aws](https://github.com/upbound/provider-aws):

- https://github.com/upbound/provider-aws/pull/938
- https://github.com/upbound/provider-aws/pull/1086

#### Issues reported

- https://github.com/crossplane/crossplane/issues/4401
- https://github.com/crossplane/docs/issues/568
- https://github.com/crossplane/upjet/issues/271
- https://github.com/crossplane/upjet/issues/295
- https://github.com/crossplane/upjet/issues/298
- https://github.com/crossplane/upjet/issues/299
- https://github.com/crossplane/upjet/issues/303

To-be-donated-to-Crossplane [provider-aws](https://github.com/upbound/provider-aws):

- https://github.com/upbound/provider-aws/pull/811
- https://github.com/upbound/provider-aws/issues/813

**Comment by jeanduplessis** [comment]
+1

**Comment by jbw976** [comment]
+1 for sure! ✅

**Comment by jbw976** [comment]
@mergenci has been invited to join the Crossplane org now ✅
