### ISSUE TITLE
MEMBERSHIP: abelhoula

### ISSUE THREAD

**Issue by abelhoula** [crossplane/org#75]
### GitHub Username
abelhoula

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [x] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [x] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [x] I am actively contributing to the Crossplane project
- [x] I have two sponsors that are current Crossplane Org members
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jbw976 
- @haarchi

### List of contributions to the Crossplane project
- https://github.com/crossplane-contrib/provider-argocd/pull/127
- https://github.com/crossplane-contrib/provider-argocd/issues/126
- https://github.com/crossplane/crossplane/issues/5272
- https://github.com/crossplane/crossplane/discussions/4974
- https://github.com/crossplane/crossplane/issues/3862

**Comment by jbw976** [comment]
Happy to sponsor here @abelhoula! 👍 

@haarchri you want to add your +1 here too?

**Comment by haarchri** [comment]
Thanks for all the contributions +1
