### ISSUE TITLE
MEMBERSHIP: tr0njavolta

### ISSUE THREAD

**Issue by tr0njavolta** [crossplane/org#77]
### GitHub Username
@tr0njavolta

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [x] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [x] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [x] I am actively contributing to the Crossplane project
- [x] I have two sponsors that are current Crossplane Org members
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jbw976 
- @bobh66 

### List of contributions to the Crossplane project
- Exclusively docs contributes
- https://github.com/crossplane/docs/pull/780
- https://github.com/crossplane/docs/pull/773
- https://github.com/crossplane/docs/pull/767

**Comment by jbw976** [comment]
+1 for sure! 💯

**Comment by bobh66** [comment]
+1 me too

**Comment by jbw976** [comment]
Invitation to join the crossplane org as a member has been sent to @tr0njavolta, check your inbox!
