### ISSUE TITLE
MEMBERSHIP: enesonus

### ISSUE THREAD

**Issue by enesonus** [crossplane/org#79]
### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [x] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [x] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [x] I am actively contributing to the Crossplane project
- [x] I have two sponsors that are current Crossplane Org members
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jbw976
- @ezgidemirel

### List of contributions to the Crossplane project
- PRs reviewed / authored
    - https://github.com/crossplane/crossplane/pull/5493
    - https://github.com/crossplane/crossplane/pull/5791
    - https://github.com/crossplane/crossplane/pull/5644
- Issues responded to
    - https://github.com/crossplane/crossplane/issues/5462
    - https://github.com/crossplane/crossplane/pull/5339

**Comment by jbw976** [comment]
+1 for sure, great contributions already made and yet to come! 🙇‍♂️

**Comment by ezgidemirel** [comment]
Definitely a big +1

**Comment by jbw976** [comment]
An invitation has been sent to @enesonus to join the Crossplane org as a member 🙇‍♂️
