### ISSUE TITLE
MEMBERSHIP: AaronME

### ISSUE THREAD

**Issue by AaronME** [crossplane/org#8]
### GitHub Username
@AaronME

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [X] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [X] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [x] I am actively contributing to the Crossplane project
- [X] I have two sponsors that are current Crossplane Org members
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @muvaf 
- @hasheddan 

### List of contributions to the Crossplane project
- https://github.com/upbound/build/pull/139

**Comment by hasheddan** [comment]
+1 from me! @AaronME I believe your contributions to the build submodule, which will unblock supporting additional architectures in Crossplane, along with your intention to continue contribution makes checking `I am actively contributing to the Crossplane project` valid, and please also do review the community membership guidelines :)

**Comment by muvaf** [comment]
+1

**Comment by jbw976** [comment]
Closed via #9
