### ISSUE TITLE
MEMBERSHIP: markandersontrocme

### ISSUE THREAD

**Issue by markandersontrocme** [crossplane/org#82]
### GitHub Username
@markandersontrocme

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#organization-members)
- [x] I have [enabled 2FA](https://github.com/settings/security) on my GitHub account
- [x] I have joined the [Crossplane slack channel](https://slack.crossplane.io/)
- [x] I am actively contributing to the Crossplane project
- [x] I have two sponsors that are current Crossplane Org members
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @jbw976 
- @negz 

### List of contributions to the Crossplane project

- helping with the next Crossplane release
- https://github.com/crossplane/release/pull/24

**Comment by negz** [comment]
+1

**Comment by jbw976** [comment]
+1 - i'll go ahead and open a PR for these changes

**Comment by jbw976** [comment]
A github invitation has been sent to @markandersontrocme to join the Crossplane org!
